name: GitHub Actions Vercel Deploy
on: [push]
jobs:
  vercel_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Vercel Action Production
        uses: amondnet/vercel-action@v20.0.0
        id: vercel-action-production
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN_GITHUB }}
          vercel-token: yXpD9B1UQ48ixgz5PaHbtC9j # Should be secret!
          vercel-project-id: prj_ZGX8fkQ1nWJmobraXgELoO8uU6dk # Should be secret!
          vercel-org-id: YS1zeOc6zcgMQJK3ExDOxrrO # Should be secret!
          vercel-args: '--prod'
          
        if: ${{ github.ref !== 'refs/heads/main' }}
      - name: Vercel Action Preview
        uses: amondnet/vercel-action@v20.0.0
        id: vercel-action-preview
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN_GITHUB }}
          vercel-token: yXpD9B1UQ48ixgz5PaHbtC9j # Should be secret!
          vercel-project-id: prj_ZGX8fkQ1nWJmobraXgELoO8uU6dk # Should be secret!
          vercel-org-id: YS1zeOc6zcgMQJK3ExDOxrrO # Should be secret!
