name: Lighthouse CI
on: push
jobs:
  lighthouse_CI:
    runs-on: ubuntu-latest
    steps:
    
    - name: Waiting for Vercel deployment
      uses: mskelton/wait-for-vercel-action@v1
      id: wait-for-vercel
      with:
        prod-url: https://headless-commerce-poc-alianza.vercel.app/
        token: yXpD9B1UQ48ixgz5PaHbtC9j
        await-build: true
    - name: Echo preview url
      run: echo ${{ steps.wait-for-vercel.outputs.url }}

    - uses: actions/checkout@v2
    - name: Audit preview URL with Lighthouse
      uses: treosh/lighthouse-ci-action@v7
      with:
        urls: |
          ${{ steps.wait-for-vercel.outputs.url }}
        uploadArtifacts: true # save results as an action artifacts
        temporaryPublicStorage: true # upload lighthouse report to the temporary storage
